%% runSolvers
%This code runs and compares the various solvers used in the ISP based on
%the data file generated by the init.m control program.

clc
clear
close all

addpath(genpath("/Users/austinrothschild/Desktop/Research/Levinson Research/Inverse Scattering/ISP-repo/InverseScatteringProblem-code/code"));
load forwardProblem.mat
%% Diag Method
filename = 'forwardProblem';
load([filename,'.mat']) 
A = FWD.U_i; %incident fields
B = FWD.U_d; %detector fields
U_s = FWD.U_s; %measured scattered field
G = FWD.G; %scattering interaction matrix
v_hadd = pinv(((A'*A).*(B*B').')); %diag method operator
v_original = FWD.V_vec; %original material
flag = 0; %change to 1 to show plots in diagMethod() function
[v] = solvers.diagMethod2(A,B,U_s,G,v_hadd,v_original,flag);

%[v1,v2,v3,v4] = solvers.diagMethod(filename, flag);
