%% runSolvers
%This code runs and compares the various solvers used in the ISP based on
%the data file generated by the init.m control program.

clc
clear
close all

addpath(genpath("/Users/austinrothschild/Desktop/Research/Levinson Research/Inverse Scattering/ISP-repo/InverseScatteringProblem-code/code"));
load forwardProblem.mat
%% Diag Method
% flag = 0; %change to 1 to show plots in diagMethod() function
% [v1, v2, v3] = solvers.diagMethod('forwardProblem',flag);

 filename = 'forwardProblem';
% flag = 1;
% [v1,v2,v3,v4] = solvers.diagMethod(filename, flag);

numTerms=2;
[v] = solvers.nTerms_ISP(filename, numTerms)